### PR TITLE
Edit Soap Exams

### LINKED ISSUE #21: Users should be able to edit existing SOAP exams.
Users should be able to edit details of an existing SOAP in the event of errors or new information that was not previously available.

AC:
- [ ] There should be an `Edit` button somewhere on the chart for users to click
- [ ] It should reopen the multi-step form, complete with validation
- [ ] The Soap Assessment on the database should be updated once saved

** For consideration there should be a time limit for how far in the future notes can be edited

### PR DESCRIPTION
**Pull request by mentalcaries**
For this PR I:
- Modified the `NewSoapAssessment` component to be reusable for the new and edit soap features. It's been renamed to `SoapAssessmentForm` and now accepts the function (create/update) that makes the API call.
- Modified the `SoapAssessmentForm` component to set the default values to the existing values of they exist, else initialize to an empty string
- Set the validation to be valid by default when editing the data (otherwise the user is not able to click "next")
- Set up a dropdown menu to access the "Edit" option (and eventually a "delete" option) to Edit the SOAP.
- Updated the DB call for Soaps so that they are sorted by most recent SOAP first
- Updated the DB call so that the SOAP is updated ONLY if the id's match (thanks @NuriyaAkh )
- Set up the Patient Soaps Card to be a scrollable area

Closes #21 

image

image

### CODE REVIEW

**Review by jeremiahfallin — CHANGES_REQUESTED** [review]
Functionally it works the way I expect it to!

One change that I think should happen before being merged is that the tabs still change position when you switch between them. It's bad UX for interactive elements to shift away from being under your mouse when the they click on things.

Placing the tabs to be at the top of the modal should fix that.

Also I think the menu button for editing is a good idea!

**Comment by mentalcaries** [comment]
> Functionally it works the way I expect it to!
> 
> One change that I think should happen before being merged is that the tabs still change position when you switch between them. It's bad UX for interactive elements to shift away from being under your mouse when the they click on things.
> 
> Placing the tabs to be at the top of the modal should fix that.
> 
> Also I think the menu button for editing is a good idea!

Thanks for reviewing this @jeremiahfallin 

The dialog height was adjusted to `80vh` and the TabContent was wrapped in a ScrollArea with `h-96`

**Review by NuriyaAkh — APPROVED** [review]
Everything works as expected! Thank you!

**Review by jeremiahfallin — APPROVED** [review]
Nice work!

**Pull request merged**
